<?php

//////////////////////////////////////////////////////////////////////////
//    DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN  //
//                                                                       //
//                   File generated by openITCOCKPIT                     //
//                                                                       //
//                        Created: 14.11.2018 13:33                      //
//////////////////////////////////////////////////////////////////////////


$config = [
    'after_export' => [
        'SSH' => [

            //Username via the SSH connection is established
            'username'        => 'nagios',

            //Path to your ssh private key file
            'private_key'     => '/var/lib/nagios/.ssh/id_rsa',

            //Path to your ssh public key file
            'public_key'      => '/var/lib/nagios/.ssh/id_rsa.pub',

            //Command to restart remote monitoring engine
            'restart_command' => 'sudo /opt/openitc/nagios/bin/restart-monitoring.sh',

            //Use rsync or PHP SSH lib to copy data
            'use_rsync'       => true,

            /**
             * A command that will be executed on the remote host
             * Be careful with this option
             * Example:
             * 'remote_command' => [
             *        'whoami',
             *        'echo 1 >> /tmp/after_export'
             * ]
             **/
            'remote_command'  => [],

            //Remote SSH port
            'port'            => 22,
        ],

        'REMOTE' => [
            //Path on the remote system were config files will be copied to
            //With ending / !!!!!!
            'path' => '/opt/openitc/nagios/etc/',
        ]
    ]
];