<?php
// Copyright (C) <2015>  <it-novum GmbH>
//
// This file is dual licensed
//
// 1.
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, version 3 of the License.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
// 2.
//  If you purchased an openITCOCKPIT Enterprise Edition you can use this file
//  under the terms of the openITCOCKPIT Enterprise Edition license agreement.
//  License agreement and license key will be shipped with the order
//  confirmation.

namespace itnovum\openITCOCKPIT\InitialDatabase;

use App\Model\Table\ServicetemplatesTable;
use Cake\Utility\Inflector;

/**
 * Class Servicetemplate
 * @package itnovum\openITCOCKPIT\InitialDatabase
 * @property ServicetemplatesTable $Table
 */
class Servicetemplate extends Importer {

    /**
     * @return bool
     */
    public function import() {
        if ($this->isTableEmpty()) {
            $data = $this->getData();
            foreach ($data as $record) {
                $entity = $this->Table->newEmptyEntity();
                $entity = $this->patchEntityAndKeepAllIds($entity, $record);
                $this->Table->save($entity);
            }
        }
    }

    /**
     * @return array
     */
    public function getData() {
        $data = [
            (int)0  => [
                'id'                                        => '1',
                'uuid'                                      => '3eb9db30-c9cf-4c25-9c69-0c3c01dc2256',
                'template_name'                             => 'Ping',
                'name'                                      => 'Ping',
                'container_id'                              => '1',
                'servicetemplatetype_id'                    => '1',
                'check_period_id'                           => '1',
                'notify_period_id'                          => '1',
                'description'                               => 'Lan-Ping',
                'command_id'                                => '3',
                'check_command_args'                        => '',
                'checkcommand_info'                         => '',
                'eventhandler_command_id'                   => '0',
                'timeperiod_id'                             => null,
                'check_interval'                            => '300',
                'retry_interval'                            => '60',
                'max_check_attempts'                        => '3',
                'first_notification_delay'                  => '0',
                'notification_interval'                     => '7200',
                'notify_on_warning'                         => '0',
                'notify_on_unknown'                         => '0',
                'notify_on_critical'                        => '1',
                'notify_on_recovery'                        => '1',
                'notify_on_flapping'                        => '0',
                'notify_on_downtime'                        => '0',
                'flap_detection_enabled'                    => '0',
                'flap_detection_on_ok'                      => '0',
                'flap_detection_on_warning'                 => '0',
                'flap_detection_on_unknown'                 => '0',
                'flap_detection_on_critical'                => '0',
                'low_flap_threshold'                        => '0',
                'high_flap_threshold'                       => '0',
                'process_performance_data'                  => '1',
                'freshness_checks_enabled'                  => '0',
                'freshness_threshold'                       => null,
                'passive_checks_enabled'                    => '0',
                'event_handler_enabled'                     => '0',
                'active_checks_enabled'                     => '1',
                'retain_status_information'                 => '0',
                'retain_nonstatus_information'              => '0',
                'notifications_enabled'                     => '0',
                'notes'                                     => '',
                'priority'                                  => '1',
                'tags'                                      => '',
                'service_url'                               => '',
                'is_volatile'                               => '0',
                'check_freshness'                           => '0',
                'created'                                   => '2015-01-05 15:20:14',
                'modified'                                  => '2015-01-15 23:46:17',
                'servicetemplateeventcommandargumentvalues' => [],
                'servicetemplatecommandargumentvalues'      => [
                    (int)0 => [
                        'id'                 => '1',
                        'commandargument_id' => '1',
                        'servicetemplate_id' => '1',
                        'value'              => '100.0,20%',
                        'created'            => '2015-01-05 15:20:14',
                        'modified'           => '2015-01-15 23:46:17'
                    ],
                    (int)1 => [
                        'id'                 => '2',
                        'commandargument_id' => '2',
                        'servicetemplate_id' => '1',
                        'value'              => '500.0,60%',
                        'created'            => '2015-01-05 15:20:14',
                        'modified'           => '2015-01-15 23:46:17'
                    ]
                ],
                'customvariables'                           => [],
                'servicegroups'                             => [],
                'contactgroups'                             => [],
                'contacts'                                  => [
                    '_ids' => [
                        (int)0 => '1'
                    ]
                ]
            ],
            (int)1  => [
                'id'                                        => '2',
                'uuid'                                      => 'fd250454-4065-4218-8e8e-4b0325eddf13',
                'template_name'                             => 'CHECK_SSH',
                'name'                                      => 'CHECK_SSH',
                'container_id'                              => '1',
                'servicetemplatetype_id'                    => '1',
                'check_period_id'                           => '1',
                'notify_period_id'                          => '1',
                'description'                               => 'SSH',
                'command_id'                                => '11',
                'check_command_args'                        => '',
                'checkcommand_info'                         => '',
                'eventhandler_command_id'                   => '0',
                'timeperiod_id'                             => null,
                'check_interval'                            => '300',
                'retry_interval'                            => '60',
                'max_check_attempts'                        => '3',
                'first_notification_delay'                  => '0',
                'notification_interval'                     => '7200',
                'notify_on_warning'                         => '0',
                'notify_on_unknown'                         => '0',
                'notify_on_critical'                        => '1',
                'notify_on_recovery'                        => '1',
                'notify_on_flapping'                        => '0',
                'notify_on_downtime'                        => '0',
                'flap_detection_enabled'                    => '0',
                'flap_detection_on_ok'                      => '0',
                'flap_detection_on_warning'                 => '0',
                'flap_detection_on_unknown'                 => '0',
                'flap_detection_on_critical'                => '0',
                'low_flap_threshold'                        => '0',
                'high_flap_threshold'                       => '0',
                'process_performance_data'                  => '0',
                'freshness_checks_enabled'                  => '0',
                'freshness_threshold'                       => null,
                'passive_checks_enabled'                    => '0',
                'event_handler_enabled'                     => '0',
                'active_checks_enabled'                     => '1',
                'retain_status_information'                 => '0',
                'retain_nonstatus_information'              => '0',
                'notifications_enabled'                     => '0',
                'notes'                                     => '',
                'priority'                                  => '1',
                'tags'                                      => '',
                'service_url'                               => '',
                'is_volatile'                               => '0',
                'check_freshness'                           => '0',
                'created'                                   => '2015-01-15 23:44:39',
                'modified'                                  => '2015-01-15 23:45:45',
                'servicetemplateeventcommandargumentvalues' => [],
                'servicetemplatecommandargumentvalues'      => [],
                'customvariables'                           => [],
                'servicegroups'                             => [],
                'contactgroups'                             => [],
                'contacts'                                  => [
                    '_ids' => [
                        (int)0 => '1'
                    ]
                ]
            ],
            (int)2  => [
                'id'                                        => '3',
                'uuid'                                      => 'cd5f7e0a-3682-4734-806d-455f1b296888',
                'template_name'                             => 'CHECK_BY_SSH',
                'name'                                      => 'CHECK_BY_SSH',
                'container_id'                              => '1',
                'servicetemplatetype_id'                    => '1',
                'check_period_id'                           => '1',
                'notify_period_id'                          => '1',
                'description'                               => 'Execute a command on a remote host',
                'command_id'                                => '23',
                'check_command_args'                        => '',
                'checkcommand_info'                         => '',
                'eventhandler_command_id'                   => '0',
                'timeperiod_id'                             => null,
                'check_interval'                            => '900',
                'retry_interval'                            => '300',
                'max_check_attempts'                        => '3',
                'first_notification_delay'                  => '0',
                'notification_interval'                     => '7200',
                'notify_on_warning'                         => '0',
                'notify_on_unknown'                         => '0',
                'notify_on_critical'                        => '1',
                'notify_on_recovery'                        => '1',
                'notify_on_flapping'                        => '0',
                'notify_on_downtime'                        => '0',
                'flap_detection_enabled'                    => '0',
                'flap_detection_on_ok'                      => '0',
                'flap_detection_on_warning'                 => '0',
                'flap_detection_on_unknown'                 => '0',
                'flap_detection_on_critical'                => '0',
                'low_flap_threshold'                        => '0',
                'high_flap_threshold'                       => '0',
                'process_performance_data'                  => '1',
                'freshness_checks_enabled'                  => '0',
                'freshness_threshold'                       => null,
                'passive_checks_enabled'                    => '0',
                'event_handler_enabled'                     => '0',
                'active_checks_enabled'                     => '1',
                'retain_status_information'                 => '0',
                'retain_nonstatus_information'              => '0',
                'notifications_enabled'                     => '0',
                'notes'                                     => '',
                'priority'                                  => '1',
                'tags'                                      => '',
                'service_url'                               => null,
                'is_volatile'                               => '0',
                'check_freshness'                           => '0',
                'created'                                   => '2015-01-15 23:47:34',
                'modified'                                  => '2015-01-15 23:47:34',
                'servicetemplateeventcommandargumentvalues' => [],
                'servicetemplatecommandargumentvalues'      => [
                    (int)0 => [
                        'id'                 => '3',
                        'commandargument_id' => '37',
                        'servicetemplate_id' => '3',
                        'value'              => '',
                        'created'            => '2015-01-15 23:47:34',
                        'modified'           => '2015-01-15 23:47:34'
                    ],
                    (int)1 => [
                        'id'                 => '4',
                        'commandargument_id' => '38',
                        'servicetemplate_id' => '3',
                        'value'              => '',
                        'created'            => '2015-01-15 23:47:34',
                        'modified'           => '2015-01-15 23:47:34'
                    ]
                ],
                'customvariables'                           => [],
                'servicegroups'                             => [],
                'contactgroups'                             => [],
                'contacts'                                  => [
                    '_ids' => [
                        (int)0 => '1'
                    ]
                ]
            ],
            (int)3  => [
                'id'                                        => '4',
                'uuid'                                      => 'eec01955-9aee-4763-b205-f3021480eee5',
                'template_name'                             => 'CHECK_DHCP',
                'name'                                      => 'CHECK_DHCP',
                'container_id'                              => '1',
                'servicetemplatetype_id'                    => '1',
                'check_period_id'                           => '1',
                'notify_period_id'                          => '1',
                'description'                               => 'Check if DHCP server returns the right IP address',
                'command_id'                                => '5',
                'check_command_args'                        => '',
                'checkcommand_info'                         => '',
                'eventhandler_command_id'                   => '0',
                'timeperiod_id'                             => null,
                'check_interval'                            => '300',
                'retry_interval'                            => '90',
                'max_check_attempts'                        => '3',
                'first_notification_delay'                  => '0',
                'notification_interval'                     => '0',
                'notify_on_warning'                         => '0',
                'notify_on_unknown'                         => '0',
                'notify_on_critical'                        => '1',
                'notify_on_recovery'                        => '1',
                'notify_on_flapping'                        => '0',
                'notify_on_downtime'                        => '0',
                'flap_detection_enabled'                    => '0',
                'flap_detection_on_ok'                      => '0',
                'flap_detection_on_warning'                 => '0',
                'flap_detection_on_unknown'                 => '0',
                'flap_detection_on_critical'                => '0',
                'low_flap_threshold'                        => '0',
                'high_flap_threshold'                       => '0',
                'process_performance_data'                  => '1',
                'freshness_checks_enabled'                  => '0',
                'freshness_threshold'                       => null,
                'passive_checks_enabled'                    => '0',
                'event_handler_enabled'                     => '0',
                'active_checks_enabled'                     => '1',
                'retain_status_information'                 => '0',
                'retain_nonstatus_information'              => '0',
                'notifications_enabled'                     => '0',
                'notes'                                     => '',
                'priority'                                  => '1',
                'tags'                                      => '',
                'service_url'                               => null,
                'is_volatile'                               => '0',
                'check_freshness'                           => '0',
                'created'                                   => '2015-01-15 23:49:21',
                'modified'                                  => '2015-01-15 23:49:21',
                'servicetemplateeventcommandargumentvalues' => [],
                'servicetemplatecommandargumentvalues'      => [],
                'customvariables'                           => [],
                'servicegroups'                             => [],
                'contactgroups'                             => [],
                'contacts'                                  => [
                    '_ids' => [
                        (int)0 => '1'
                    ]
                ]
            ],
            (int)4  => [
                'id'                                        => '5',
                'uuid'                                      => '632cbb02-4046-4406-8bcc-4cfe0befbc0c',
                'template_name'                             => 'CHECK_FTP',
                'name'                                      => 'CHECK_FTP',
                'container_id'                              => '1',
                'servicetemplatetype_id'                    => '1',
                'check_period_id'                           => '1',
                'notify_period_id'                          => '1',
                'description'                               => 'Test a FTP connection for given host',
                'command_id'                                => '6',
                'check_command_args'                        => '',
                'checkcommand_info'                         => '',
                'eventhandler_command_id'                   => '0',
                'timeperiod_id'                             => null,
                'check_interval'                            => '300',
                'retry_interval'                            => '90',
                'max_check_attempts'                        => '3',
                'first_notification_delay'                  => '0',
                'notification_interval'                     => '7200',
                'notify_on_warning'                         => '0',
                'notify_on_unknown'                         => '0',
                'notify_on_critical'                        => '1',
                'notify_on_recovery'                        => '1',
                'notify_on_flapping'                        => '0',
                'notify_on_downtime'                        => '0',
                'flap_detection_enabled'                    => '0',
                'flap_detection_on_ok'                      => '0',
                'flap_detection_on_warning'                 => '0',
                'flap_detection_on_unknown'                 => '0',
                'flap_detection_on_critical'                => '0',
                'low_flap_threshold'                        => '0',
                'high_flap_threshold'                       => '0',
                'process_performance_data'                  => '1',
                'freshness_checks_enabled'                  => '0',
                'freshness_threshold'                       => null,
                'passive_checks_enabled'                    => '0',
                'event_handler_enabled'                     => '0',
                'active_checks_enabled'                     => '1',
                'retain_status_information'                 => '0',
                'retain_nonstatus_information'              => '0',
                'notifications_enabled'                     => '0',
                'notes'                                     => '',
                'priority'                                  => '1',
                'tags'                                      => '',
                'service_url'                               => null,
                'is_volatile'                               => '0',
                'check_freshness'                           => '0',
                'created'                                   => '2015-01-15 23:50:41',
                'modified'                                  => '2015-01-15 23:50:41',
                'servicetemplateeventcommandargumentvalues' => [],
                'servicetemplatecommandargumentvalues'      => [],
                'customvariables'                           => [],
                'servicegroups'                             => [],
                'contactgroups'                             => [],
                'contacts'                                  => [
                    '_ids' => [
                        (int)0 => '1'
                    ]
                ]
            ],
            (int)5  => [
                'id'                                        => '6',
                'uuid'                                      => 'b987e6c0-135d-4034-987a-18c65b111fae',
                'template_name'                             => 'CHECK_HTTP',
                'name'                                      => 'CHECK_HTTP',
                'container_id'                              => '1',
                'servicetemplatetype_id'                    => '1',
                'check_period_id'                           => '1',
                'notify_period_id'                          => '1',
                'description'                               => 'Send request to an HTTP server',
                'command_id'                                => '7',
                'check_command_args'                        => '',
                'checkcommand_info'                         => '',
                'eventhandler_command_id'                   => '0',
                'timeperiod_id'                             => null,
                'check_interval'                            => '300',
                'retry_interval'                            => '90',
                'max_check_attempts'                        => '3',
                'first_notification_delay'                  => '0',
                'notification_interval'                     => '0',
                'notify_on_warning'                         => '0',
                'notify_on_unknown'                         => '0',
                'notify_on_critical'                        => '1',
                'notify_on_recovery'                        => '1',
                'notify_on_flapping'                        => '0',
                'notify_on_downtime'                        => '0',
                'flap_detection_enabled'                    => '0',
                'flap_detection_on_ok'                      => '0',
                'flap_detection_on_warning'                 => '0',
                'flap_detection_on_unknown'                 => '0',
                'flap_detection_on_critical'                => '0',
                'low_flap_threshold'                        => '0',
                'high_flap_threshold'                       => '0',
                'process_performance_data'                  => '1',
                'freshness_checks_enabled'                  => '0',
                'freshness_threshold'                       => null,
                'passive_checks_enabled'                    => '0',
                'event_handler_enabled'                     => '0',
                'active_checks_enabled'                     => '1',
                'retain_status_information'                 => '0',
                'retain_nonstatus_information'              => '0',
                'notifications_enabled'                     => '0',
                'notes'                                     => '',
                'priority'                                  => '1',
                'tags'                                      => '',
                'service_url'                               => null,
                'is_volatile'                               => '0',
                'check_freshness'                           => '0',
                'created'                                   => '2015-01-15 23:51:53',
                'modified'                                  => '2015-01-15 23:51:53',
                'servicetemplateeventcommandargumentvalues' => [],
                'servicetemplatecommandargumentvalues'      => [
                    (int)0 => [
                        'id'                 => '5',
                        'commandargument_id' => '8',
                        'servicetemplate_id' => '6',
                        'value'              => '1',
                        'created'            => '2015-01-15 23:51:53',
                        'modified'           => '2015-01-15 23:51:53'
                    ],
                    (int)1 => [
                        'id'                 => '6',
                        'commandargument_id' => '9',
                        'servicetemplate_id' => '6',
                        'value'              => '2',
                        'created'            => '2015-01-15 23:51:53',
                        'modified'           => '2015-01-15 23:51:53'
                    ],
                    (int)2 => [
                        'id'                 => '7',
                        'commandargument_id' => '10',
                        'servicetemplate_id' => '6',
                        'value'              => '/',
                        'created'            => '2015-01-15 23:51:53',
                        'modified'           => '2015-01-15 23:51:53'
                    ]
                ],
                'customvariables'                           => [],
                'servicegroups'                             => [],
                'contactgroups'                             => [],
                'contacts'                                  => [
                    '_ids' => [
                        (int)0 => '1'
                    ]
                ]
            ],
            (int)6  => [
                'id'                                        => '7',
                'uuid'                                      => 'b12e5fcd-eccc-43f9-8c84-921329e56c92',
                'template_name'                             => 'CHECK_HTTPS',
                'name'                                      => 'CHECK_HTTPS',
                'container_id'                              => '1',
                'servicetemplatetype_id'                    => '1',
                'check_period_id'                           => '1',
                'notify_period_id'                          => '1',
                'description'                               => 'Send request to an HTTPS server',
                'command_id'                                => '8',
                'check_command_args'                        => '',
                'checkcommand_info'                         => '',
                'eventhandler_command_id'                   => '0',
                'timeperiod_id'                             => null,
                'check_interval'                            => '300',
                'retry_interval'                            => '90',
                'max_check_attempts'                        => '3',
                'first_notification_delay'                  => '0',
                'notification_interval'                     => '7200',
                'notify_on_warning'                         => '0',
                'notify_on_unknown'                         => '0',
                'notify_on_critical'                        => '1',
                'notify_on_recovery'                        => '1',
                'notify_on_flapping'                        => '0',
                'notify_on_downtime'                        => '0',
                'flap_detection_enabled'                    => '0',
                'flap_detection_on_ok'                      => '0',
                'flap_detection_on_warning'                 => '0',
                'flap_detection_on_unknown'                 => '0',
                'flap_detection_on_critical'                => '0',
                'low_flap_threshold'                        => '0',
                'high_flap_threshold'                       => '0',
                'process_performance_data'                  => '1',
                'freshness_checks_enabled'                  => '0',
                'freshness_threshold'                       => null,
                'passive_checks_enabled'                    => '0',
                'event_handler_enabled'                     => '0',
                'active_checks_enabled'                     => '1',
                'retain_status_information'                 => '0',
                'retain_nonstatus_information'              => '0',
                'notifications_enabled'                     => '0',
                'notes'                                     => '',
                'priority'                                  => '1',
                'tags'                                      => '',
                'service_url'                               => null,
                'is_volatile'                               => '0',
                'check_freshness'                           => '0',
                'created'                                   => '2015-01-15 23:52:49',
                'modified'                                  => '2015-01-15 23:52:49',
                'servicetemplateeventcommandargumentvalues' => [],
                'servicetemplatecommandargumentvalues'      => [
                    (int)0 => [
                        'id'                 => '8',
                        'commandargument_id' => '11',
                        'servicetemplate_id' => '7',
                        'value'              => '1',
                        'created'            => '2015-01-15 23:52:49',
                        'modified'           => '2015-01-15 23:52:49'
                    ],
                    (int)1 => [
                        'id'                 => '9',
                        'commandargument_id' => '12',
                        'servicetemplate_id' => '7',
                        'value'              => '2',
                        'created'            => '2015-01-15 23:52:49',
                        'modified'           => '2015-01-15 23:52:49'
                    ],
                    (int)2 => [
                        'id'                 => '10',
                        'commandargument_id' => '13',
                        'servicetemplate_id' => '7',
                        'value'              => '/',
                        'created'            => '2015-01-15 23:52:49',
                        'modified'           => '2015-01-15 23:52:49'
                    ]
                ],
                'customvariables'                           => [],
                'servicegroups'                             => [],
                'contactgroups'                             => [],
                'contacts'                                  => [
                    '_ids' => [
                        (int)0 => '1'
                    ]
                ]
            ],
            (int)7  => [
                'id'                                        => '8',
                'uuid'                                      => '354c1e0e-bd09-48e0-bbbe-eb98a4059454',
                'template_name'                             => 'CHECK_LOCAL_DISK',
                'name'                                      => 'CHECK_LOCAL_DISK',
                'container_id'                              => '1',
                'servicetemplatetype_id'                    => '1',
                'check_period_id'                           => '1',
                'notify_period_id'                          => '1',
                'description'                               => 'Checks a local disk of the openITCOCKPIT Server',
                'command_id'                                => '17',
                'check_command_args'                        => '',
                'checkcommand_info'                         => '',
                'eventhandler_command_id'                   => '0',
                'timeperiod_id'                             => null,
                'check_interval'                            => '1800',
                'retry_interval'                            => '300',
                'max_check_attempts'                        => '2',
                'first_notification_delay'                  => '0',
                'notification_interval'                     => '7200',
                'notify_on_warning'                         => '0',
                'notify_on_unknown'                         => '0',
                'notify_on_critical'                        => '1',
                'notify_on_recovery'                        => '1',
                'notify_on_flapping'                        => '0',
                'notify_on_downtime'                        => '0',
                'flap_detection_enabled'                    => '0',
                'flap_detection_on_ok'                      => '0',
                'flap_detection_on_warning'                 => '0',
                'flap_detection_on_unknown'                 => '0',
                'flap_detection_on_critical'                => '0',
                'low_flap_threshold'                        => '0',
                'high_flap_threshold'                       => '0',
                'process_performance_data'                  => '1',
                'freshness_checks_enabled'                  => '0',
                'freshness_threshold'                       => null,
                'passive_checks_enabled'                    => '0',
                'event_handler_enabled'                     => '0',
                'active_checks_enabled'                     => '1',
                'retain_status_information'                 => '0',
                'retain_nonstatus_information'              => '0',
                'notifications_enabled'                     => '0',
                'notes'                                     => '',
                'priority'                                  => '1',
                'tags'                                      => '',
                'service_url'                               => null,
                'is_volatile'                               => '0',
                'check_freshness'                           => '0',
                'created'                                   => '2015-01-15 23:55:07',
                'modified'                                  => '2015-01-15 23:55:07',
                'servicetemplateeventcommandargumentvalues' => [],
                'servicetemplatecommandargumentvalues'      => [
                    (int)0 => [
                        'id'                 => '11',
                        'commandargument_id' => '23',
                        'servicetemplate_id' => '8',
                        'value'              => '20',
                        'created'            => '2015-01-15 23:55:07',
                        'modified'           => '2015-01-15 23:55:07'
                    ],
                    (int)1 => [
                        'id'                 => '12',
                        'commandargument_id' => '24',
                        'servicetemplate_id' => '8',
                        'value'              => '10',
                        'created'            => '2015-01-15 23:55:07',
                        'modified'           => '2015-01-15 23:55:07'
                    ],
                    (int)2 => [
                        'id'                 => '13',
                        'commandargument_id' => '25',
                        'servicetemplate_id' => '8',
                        'value'              => '/',
                        'created'            => '2015-01-15 23:55:07',
                        'modified'           => '2015-01-15 23:55:07'
                    ]
                ],
                'customvariables'                           => [],
                'servicegroups'                             => [],
                'contactgroups'                             => [],
                'contacts'                                  => [
                    '_ids' => [
                        (int)0 => '1'
                    ]
                ]
            ],
            (int)8  => [
                'id'                                        => '9',
                'uuid'                                      => 'c673cc09-c46a-4916-8e42-85cb0e68f1e6',
                'template_name'                             => 'CHECK_LOCAL_LOAD',
                'name'                                      => 'CHECK_LOCAL_LOAD',
                'container_id'                              => '1',
                'servicetemplatetype_id'                    => '1',
                'check_period_id'                           => '1',
                'notify_period_id'                          => '1',
                'description'                               => 'Checks the CPU load of the openITCOCKPIT Server',
                'command_id'                                => '19',
                'check_command_args'                        => '',
                'checkcommand_info'                         => '',
                'eventhandler_command_id'                   => '0',
                'timeperiod_id'                             => null,
                'check_interval'                            => '300',
                'retry_interval'                            => '90',
                'max_check_attempts'                        => '3',
                'first_notification_delay'                  => '0',
                'notification_interval'                     => '7200',
                'notify_on_warning'                         => '0',
                'notify_on_unknown'                         => '0',
                'notify_on_critical'                        => '1',
                'notify_on_recovery'                        => '1',
                'notify_on_flapping'                        => '0',
                'notify_on_downtime'                        => '0',
                'flap_detection_enabled'                    => '0',
                'flap_detection_on_ok'                      => '0',
                'flap_detection_on_warning'                 => '0',
                'flap_detection_on_unknown'                 => '0',
                'flap_detection_on_critical'                => '0',
                'low_flap_threshold'                        => '0',
                'high_flap_threshold'                       => '0',
                'process_performance_data'                  => '1',
                'freshness_checks_enabled'                  => '0',
                'freshness_threshold'                       => null,
                'passive_checks_enabled'                    => '0',
                'event_handler_enabled'                     => '0',
                'active_checks_enabled'                     => '1',
                'retain_status_information'                 => '0',
                'retain_nonstatus_information'              => '0',
                'notifications_enabled'                     => '0',
                'notes'                                     => '',
                'priority'                                  => '1',
                'tags'                                      => '',
                'service_url'                               => null,
                'is_volatile'                               => '0',
                'check_freshness'                           => '0',
                'created'                                   => '2015-01-15 23:56:25',
                'modified'                                  => '2015-01-15 23:56:25',
                'servicetemplateeventcommandargumentvalues' => [],
                'servicetemplatecommandargumentvalues'      => [
                    (int)0 => [
                        'id'                 => '14',
                        'commandargument_id' => '28',
                        'servicetemplate_id' => '9',
                        'value'              => '7.0,6.0,5.0',
                        'created'            => '2015-01-15 23:56:25',
                        'modified'           => '2015-01-15 23:56:25'
                    ],
                    (int)1 => [
                        'id'                 => '15',
                        'commandargument_id' => '29',
                        'servicetemplate_id' => '9',
                        'value'              => '10.0,7.0,6.0',
                        'created'            => '2015-01-15 23:56:25',
                        'modified'           => '2015-01-15 23:56:25'
                    ]
                ],
                'customvariables'                           => [],
                'servicegroups'                             => [],
                'contactgroups'                             => [],
                'contacts'                                  => [
                    '_ids' => [
                        (int)0 => '1'
                    ]
                ]
            ],
            (int)9  => [
                'id'                                        => '10',
                'uuid'                                      => '90aefb61-c818-4bd6-818c-c9e6174b3e13',
                'template_name'                             => 'CHECK_LOCAL_MAILQ',
                'name'                                      => 'CHECK_LOCAL_MAILQ',
                'container_id'                              => '1',
                'servicetemplatetype_id'                    => '1',
                'check_period_id'                           => '1',
                'notify_period_id'                          => '1',
                'description'                               => 'Checks the mailq of the openITCOCKPIT Server',
                'command_id'                                => '20',
                'check_command_args'                        => '',
                'checkcommand_info'                         => '',
                'eventhandler_command_id'                   => '0',
                'timeperiod_id'                             => null,
                'check_interval'                            => '900',
                'retry_interval'                            => '300',
                'max_check_attempts'                        => '2',
                'first_notification_delay'                  => '0',
                'notification_interval'                     => '7200',
                'notify_on_warning'                         => '0',
                'notify_on_unknown'                         => '0',
                'notify_on_critical'                        => '1',
                'notify_on_recovery'                        => '1',
                'notify_on_flapping'                        => '0',
                'notify_on_downtime'                        => '0',
                'flap_detection_enabled'                    => '0',
                'flap_detection_on_ok'                      => '0',
                'flap_detection_on_warning'                 => '0',
                'flap_detection_on_unknown'                 => '0',
                'flap_detection_on_critical'                => '0',
                'low_flap_threshold'                        => '0',
                'high_flap_threshold'                       => '0',
                'process_performance_data'                  => '1',
                'freshness_checks_enabled'                  => '0',
                'freshness_threshold'                       => null,
                'passive_checks_enabled'                    => '0',
                'event_handler_enabled'                     => '0',
                'active_checks_enabled'                     => '1',
                'retain_status_information'                 => '0',
                'retain_nonstatus_information'              => '0',
                'notifications_enabled'                     => '0',
                'notes'                                     => '',
                'priority'                                  => '1',
                'tags'                                      => '',
                'service_url'                               => null,
                'is_volatile'                               => '0',
                'check_freshness'                           => '0',
                'created'                                   => '2015-01-15 23:57:39',
                'modified'                                  => '2015-01-15 23:57:39',
                'servicetemplateeventcommandargumentvalues' => [],
                'servicetemplatecommandargumentvalues'      => [
                    (int)0 => [
                        'id'                 => '16',
                        'commandargument_id' => '30',
                        'servicetemplate_id' => '10',
                        'value'              => '25',
                        'created'            => '2015-01-15 23:57:39',
                        'modified'           => '2015-01-15 23:57:39'
                    ],
                    (int)1 => [
                        'id'                 => '17',
                        'commandargument_id' => '31',
                        'servicetemplate_id' => '10',
                        'value'              => '50',
                        'created'            => '2015-01-15 23:57:39',
                        'modified'           => '2015-01-15 23:57:39'
                    ]
                ],
                'customvariables'                           => [],
                'servicegroups'                             => [],
                'contactgroups'                             => [],
                'contacts'                                  => [
                    '_ids' => [
                        (int)0 => '1'
                    ]
                ]
            ],
            (int)10 => [
                'id'                                        => '11',
                'uuid'                                      => '91bc9075-64b2-4054-a39d-c2981cd6bd01',
                'template_name'                             => 'CHECK_LOCAL_PROC',
                'name'                                      => 'CHECK_LOCAL_PROC',
                'container_id'                              => '1',
                'servicetemplatetype_id'                    => '1',
                'check_period_id'                           => '1',
                'notify_period_id'                          => '1',
                'description'                               => 'Check if a process is running on openITCOCKPIT server',
                'command_id'                                => '21',
                'check_command_args'                        => '',
                'checkcommand_info'                         => '',
                'eventhandler_command_id'                   => '0',
                'timeperiod_id'                             => null,
                'check_interval'                            => '300',
                'retry_interval'                            => '120',
                'max_check_attempts'                        => '3',
                'first_notification_delay'                  => '0',
                'notification_interval'                     => '7200',
                'notify_on_warning'                         => '0',
                'notify_on_unknown'                         => '0',
                'notify_on_critical'                        => '1',
                'notify_on_recovery'                        => '1',
                'notify_on_flapping'                        => '0',
                'notify_on_downtime'                        => '0',
                'flap_detection_enabled'                    => '0',
                'flap_detection_on_ok'                      => '0',
                'flap_detection_on_warning'                 => '0',
                'flap_detection_on_unknown'                 => '0',
                'flap_detection_on_critical'                => '0',
                'low_flap_threshold'                        => '0',
                'high_flap_threshold'                       => '0',
                'process_performance_data'                  => '1',
                'freshness_checks_enabled'                  => '0',
                'freshness_threshold'                       => null,
                'passive_checks_enabled'                    => '0',
                'event_handler_enabled'                     => '0',
                'active_checks_enabled'                     => '1',
                'retain_status_information'                 => '0',
                'retain_nonstatus_information'              => '0',
                'notifications_enabled'                     => '0',
                'notes'                                     => '',
                'priority'                                  => '1',
                'tags'                                      => '',
                'service_url'                               => null,
                'is_volatile'                               => '0',
                'check_freshness'                           => '0',
                'created'                                   => '2015-01-16 00:01:26',
                'modified'                                  => '2015-01-16 00:01:26',
                'servicetemplateeventcommandargumentvalues' => [],
                'servicetemplatecommandargumentvalues'      => [
                    (int)0 => [
                        'id'                 => '18',
                        'commandargument_id' => '32',
                        'servicetemplate_id' => '11',
                        'value'              => '1:10',
                        'created'            => '2015-01-16 00:01:26',
                        'modified'           => '2015-01-16 00:01:26'
                    ],
                    (int)1 => [
                        'id'                 => '19',
                        'commandargument_id' => '33',
                        'servicetemplate_id' => '11',
                        'value'              => '1:20',
                        'created'            => '2015-01-16 00:01:26',
                        'modified'           => '2015-01-16 00:01:26'
                    ],
                    (int)2 => [
                        'id'                 => '20',
                        'commandargument_id' => '34',
                        'servicetemplate_id' => '11',
                        'value'              => '/usr/sbin/nginx',
                        'created'            => '2015-01-16 00:01:26',
                        'modified'           => '2015-01-16 00:01:26'
                    ]
                ],
                'customvariables'                           => [],
                'servicegroups'                             => [],
                'contactgroups'                             => [],
                'contacts'                                  => [
                    '_ids' => [
                        (int)0 => '1'
                    ]
                ]
            ],
            (int)11 => [
                'id'                                        => '12',
                'uuid'                                      => 'b7e5c7a7-ed33-465f-ab8e-45059cb679fe',
                'template_name'                             => 'CHECK_LOCAL_PROCS_TOTAL',
                'name'                                      => 'CHECK_LOCAL_PROCS_TOTAL',
                'container_id'                              => '1',
                'servicetemplatetype_id'                    => '1',
                'check_period_id'                           => '1',
                'notify_period_id'                          => '1',
                'description'                               => 'Checks how many processes are running on openITCOCKPIT Server',
                'command_id'                                => '22',
                'check_command_args'                        => '',
                'checkcommand_info'                         => '',
                'eventhandler_command_id'                   => '0',
                'timeperiod_id'                             => null,
                'check_interval'                            => '300',
                'retry_interval'                            => '90',
                'max_check_attempts'                        => '3',
                'first_notification_delay'                  => '0',
                'notification_interval'                     => '7200',
                'notify_on_warning'                         => '0',
                'notify_on_unknown'                         => '0',
                'notify_on_critical'                        => '1',
                'notify_on_recovery'                        => '1',
                'notify_on_flapping'                        => '0',
                'notify_on_downtime'                        => '0',
                'flap_detection_enabled'                    => '0',
                'flap_detection_on_ok'                      => '0',
                'flap_detection_on_warning'                 => '0',
                'flap_detection_on_unknown'                 => '0',
                'flap_detection_on_critical'                => '0',
                'low_flap_threshold'                        => '0',
                'high_flap_threshold'                       => '0',
                'process_performance_data'                  => '1',
                'freshness_checks_enabled'                  => '0',
                'freshness_threshold'                       => null,
                'passive_checks_enabled'                    => '0',
                'event_handler_enabled'                     => '0',
                'active_checks_enabled'                     => '1',
                'retain_status_information'                 => '0',
                'retain_nonstatus_information'              => '0',
                'notifications_enabled'                     => '0',
                'notes'                                     => '',
                'priority'                                  => '1',
                'tags'                                      => '',
                'service_url'                               => null,
                'is_volatile'                               => '0',
                'check_freshness'                           => '0',
                'created'                                   => '2015-01-16 00:03:20',
                'modified'                                  => '2015-01-16 00:03:20',
                'servicetemplateeventcommandargumentvalues' => [],
                'servicetemplatecommandargumentvalues'      => [
                    (int)0 => [
                        'id'                 => '21',
                        'commandargument_id' => '35',
                        'servicetemplate_id' => '12',
                        'value'              => '',
                        'created'            => '2015-01-16 00:03:20',
                        'modified'           => '2015-01-16 00:03:20'
                    ],
                    (int)1 => [
                        'id'                 => '22',
                        'commandargument_id' => '36',
                        'servicetemplate_id' => '12',
                        'value'              => '',
                        'created'            => '2015-01-16 00:03:20',
                        'modified'           => '2015-01-16 00:03:20'
                    ]
                ],
                'customvariables'                           => [],
                'servicegroups'                             => [],
                'contactgroups'                             => [],
                'contacts'                                  => [
                    '_ids' => [
                        (int)0 => '1'
                    ]
                ]
            ],
            (int)12 => [
                'id'                                        => '13',
                'uuid'                                      => '5b0b27c4-6e70-454b-a778-b7b050910abb',
                'template_name'                             => 'CHECK_LOCAL_USERS',
                'name'                                      => 'CHECK_LOCAL_USERS',
                'container_id'                              => '1',
                'servicetemplatetype_id'                    => '1',
                'check_period_id'                           => '1',
                'notify_period_id'                          => '1',
                'description'                               => 'Checks how many users are logged in to the openITCOCKPIT server backend',
                'command_id'                                => '18',
                'check_command_args'                        => '',
                'checkcommand_info'                         => '',
                'eventhandler_command_id'                   => '0',
                'timeperiod_id'                             => null,
                'check_interval'                            => '300',
                'retry_interval'                            => '60',
                'max_check_attempts'                        => '3',
                'first_notification_delay'                  => '0',
                'notification_interval'                     => '7200',
                'notify_on_warning'                         => '0',
                'notify_on_unknown'                         => '0',
                'notify_on_critical'                        => '1',
                'notify_on_recovery'                        => '1',
                'notify_on_flapping'                        => '0',
                'notify_on_downtime'                        => '0',
                'flap_detection_enabled'                    => '0',
                'flap_detection_on_ok'                      => '0',
                'flap_detection_on_warning'                 => '0',
                'flap_detection_on_unknown'                 => '0',
                'flap_detection_on_critical'                => '0',
                'low_flap_threshold'                        => '0',
                'high_flap_threshold'                       => '0',
                'process_performance_data'                  => '1',
                'freshness_checks_enabled'                  => '0',
                'freshness_threshold'                       => null,
                'passive_checks_enabled'                    => '0',
                'event_handler_enabled'                     => '0',
                'active_checks_enabled'                     => '1',
                'retain_status_information'                 => '0',
                'retain_nonstatus_information'              => '0',
                'notifications_enabled'                     => '0',
                'notes'                                     => '',
                'priority'                                  => '1',
                'tags'                                      => '',
                'service_url'                               => null,
                'is_volatile'                               => '0',
                'check_freshness'                           => '0',
                'created'                                   => '2015-01-16 00:04:24',
                'modified'                                  => '2015-01-16 00:04:24',
                'servicetemplateeventcommandargumentvalues' => [],
                'servicetemplatecommandargumentvalues'      => [
                    (int)0 => [
                        'id'                 => '23',
                        'commandargument_id' => '26',
                        'servicetemplate_id' => '13',
                        'value'              => '3',
                        'created'            => '2015-01-16 00:04:24',
                        'modified'           => '2015-01-16 00:04:24'
                    ],
                    (int)1 => [
                        'id'                 => '24',
                        'commandargument_id' => '27',
                        'servicetemplate_id' => '13',
                        'value'              => '7',
                        'created'            => '2015-01-16 00:04:24',
                        'modified'           => '2015-01-16 00:04:24'
                    ]
                ],
                'customvariables'                           => [],
                'servicegroups'                             => [],
                'contactgroups'                             => [],
                'contacts'                                  => [
                    '_ids' => [
                        (int)0 => '1'
                    ]
                ]
            ],
            (int)13 => [
                'id'                                        => '14',
                'uuid'                                      => 'a4773ab9-ed5f-4395-b0c7-bb98bb975b06',
                'template_name'                             => 'CHECK_TCP',
                'name'                                      => 'CHECK_TCP',
                'container_id'                              => '1',
                'servicetemplatetype_id'                    => '1',
                'check_period_id'                           => '1',
                'notify_period_id'                          => '1',
                'description'                               => 'Checks a TCP port',
                'command_id'                                => '10',
                'check_command_args'                        => '',
                'checkcommand_info'                         => '',
                'eventhandler_command_id'                   => '0',
                'timeperiod_id'                             => null,
                'check_interval'                            => '300',
                'retry_interval'                            => '90',
                'max_check_attempts'                        => '3',
                'first_notification_delay'                  => '0',
                'notification_interval'                     => '7200',
                'notify_on_warning'                         => '0',
                'notify_on_unknown'                         => '0',
                'notify_on_critical'                        => '1',
                'notify_on_recovery'                        => '1',
                'notify_on_flapping'                        => '0',
                'notify_on_downtime'                        => '0',
                'flap_detection_enabled'                    => '0',
                'flap_detection_on_ok'                      => '0',
                'flap_detection_on_warning'                 => '0',
                'flap_detection_on_unknown'                 => '0',
                'flap_detection_on_critical'                => '0',
                'low_flap_threshold'                        => '0',
                'high_flap_threshold'                       => '0',
                'process_performance_data'                  => '1',
                'freshness_checks_enabled'                  => '0',
                'freshness_threshold'                       => null,
                'passive_checks_enabled'                    => '0',
                'event_handler_enabled'                     => '0',
                'active_checks_enabled'                     => '1',
                'retain_status_information'                 => '0',
                'retain_nonstatus_information'              => '0',
                'notifications_enabled'                     => '0',
                'notes'                                     => '',
                'priority'                                  => '1',
                'tags'                                      => '',
                'service_url'                               => null,
                'is_volatile'                               => '0',
                'check_freshness'                           => '0',
                'created'                                   => '2015-01-16 00:05:27',
                'modified'                                  => '2015-01-16 00:05:27',
                'servicetemplateeventcommandargumentvalues' => [],
                'servicetemplatecommandargumentvalues'      => [
                    (int)0 => [
                        'id'                 => '25',
                        'commandargument_id' => '14',
                        'servicetemplate_id' => '14',
                        'value'              => '',
                        'created'            => '2015-01-16 00:05:27',
                        'modified'           => '2015-01-16 00:05:27'
                    ]
                ],
                'customvariables'                           => [],
                'servicegroups'                             => [],
                'contactgroups'                             => [],
                'contacts'                                  => [
                    '_ids' => [
                        (int)0 => '1'
                    ]
                ]
            ],
            (int)14 => [
                'id'                                        => '15',
                'uuid'                                      => '70ef8cb7-b253-4b81-9515-335e0ade1d8f',
                'template_name'                             => 'CHECK_TELNET',
                'name'                                      => 'CHECK_TELNET',
                'container_id'                              => '1',
                'servicetemplatetype_id'                    => '1',
                'check_period_id'                           => '1',
                'notify_period_id'                          => '1',
                'description'                               => 'Check if a telnet server is running on target host',
                'command_id'                                => '9',
                'check_command_args'                        => '',
                'checkcommand_info'                         => '',
                'eventhandler_command_id'                   => '0',
                'timeperiod_id'                             => null,
                'check_interval'                            => '300',
                'retry_interval'                            => '60',
                'max_check_attempts'                        => '3',
                'first_notification_delay'                  => '0',
                'notification_interval'                     => '7200',
                'notify_on_warning'                         => '0',
                'notify_on_unknown'                         => '0',
                'notify_on_critical'                        => '1',
                'notify_on_recovery'                        => '1',
                'notify_on_flapping'                        => '0',
                'notify_on_downtime'                        => '0',
                'flap_detection_enabled'                    => '0',
                'flap_detection_on_ok'                      => '0',
                'flap_detection_on_warning'                 => '0',
                'flap_detection_on_unknown'                 => '0',
                'flap_detection_on_critical'                => '0',
                'low_flap_threshold'                        => '0',
                'high_flap_threshold'                       => '0',
                'process_performance_data'                  => '1',
                'freshness_checks_enabled'                  => '0',
                'freshness_threshold'                       => null,
                'passive_checks_enabled'                    => '0',
                'event_handler_enabled'                     => '0',
                'active_checks_enabled'                     => '1',
                'retain_status_information'                 => '0',
                'retain_nonstatus_information'              => '0',
                'notifications_enabled'                     => '0',
                'notes'                                     => '',
                'priority'                                  => '1',
                'tags'                                      => '',
                'service_url'                               => null,
                'is_volatile'                               => '0',
                'check_freshness'                           => '0',
                'created'                                   => '2015-01-16 00:06:18',
                'modified'                                  => '2015-01-16 00:06:18',
                'servicetemplateeventcommandargumentvalues' => [],
                'servicetemplatecommandargumentvalues'      => [],
                'customvariables'                           => [],
                'servicegroups'                             => [],
                'contactgroups'                             => [],
                'contacts'                                  => [
                    '_ids' => [
                        (int)0 => '1'
                    ]
                ]
            ],
            (int)15 => [
                'id'                                        => '16',
                'uuid'                                      => '52ac5010-4014-41c2-ba3a-74bc765e442d',
                'template_name'                             => 'CHECK_SMTP',
                'name'                                      => 'CHECK_SMTP',
                'container_id'                              => '1',
                'servicetemplatetype_id'                    => '1',
                'check_period_id'                           => '1',
                'notify_period_id'                          => '1',
                'description'                               => 'Check if a SNTP server is running on target host',
                'command_id'                                => '12',
                'check_command_args'                        => '',
                'checkcommand_info'                         => '',
                'eventhandler_command_id'                   => '0',
                'timeperiod_id'                             => null,
                'check_interval'                            => '300',
                'retry_interval'                            => '90',
                'max_check_attempts'                        => '3',
                'first_notification_delay'                  => '0',
                'notification_interval'                     => '7200',
                'notify_on_warning'                         => '0',
                'notify_on_unknown'                         => '0',
                'notify_on_critical'                        => '1',
                'notify_on_recovery'                        => '1',
                'notify_on_flapping'                        => '0',
                'notify_on_downtime'                        => '0',
                'flap_detection_enabled'                    => '0',
                'flap_detection_on_ok'                      => '0',
                'flap_detection_on_warning'                 => '0',
                'flap_detection_on_unknown'                 => '0',
                'flap_detection_on_critical'                => '0',
                'low_flap_threshold'                        => '0',
                'high_flap_threshold'                       => '0',
                'process_performance_data'                  => '1',
                'freshness_checks_enabled'                  => '0',
                'freshness_threshold'                       => null,
                'passive_checks_enabled'                    => '0',
                'event_handler_enabled'                     => '0',
                'active_checks_enabled'                     => '1',
                'retain_status_information'                 => '0',
                'retain_nonstatus_information'              => '0',
                'notifications_enabled'                     => '0',
                'notes'                                     => '',
                'priority'                                  => '1',
                'tags'                                      => '',
                'service_url'                               => null,
                'is_volatile'                               => '0',
                'check_freshness'                           => '0',
                'created'                                   => '2015-01-16 00:07:52',
                'modified'                                  => '2015-01-16 00:07:52',
                'servicetemplateeventcommandargumentvalues' => [],
                'servicetemplatecommandargumentvalues'      => [
                    (int)0 => [
                        'id'                 => '26',
                        'commandargument_id' => '15',
                        'servicetemplate_id' => '16',
                        'value'              => '2',
                        'created'            => '2015-01-16 00:07:52',
                        'modified'           => '2015-01-16 00:07:52'
                    ],
                    (int)1 => [
                        'id'                 => '27',
                        'commandargument_id' => '16',
                        'servicetemplate_id' => '16',
                        'value'              => '5',
                        'created'            => '2015-01-16 00:07:52',
                        'modified'           => '2015-01-16 00:07:52'
                    ]
                ],
                'customvariables'                           => [],
                'servicegroups'                             => [],
                'contactgroups'                             => [],
                'contacts'                                  => [
                    '_ids' => [
                        (int)0 => '1'
                    ]
                ]
            ],
            (int)16 => [
                'id'                                        => '17',
                'uuid'                                      => 'b80db4b7-3148-4c39-9337-d89d367b9669',
                'template_name'                             => 'CHECK_NTP_PEER',
                'name'                                      => 'CHECK_NTP_PEER',
                'container_id'                              => '1',
                'servicetemplatetype_id'                    => '1',
                'check_period_id'                           => '1',
                'notify_period_id'                          => '1',
                'description'                               => 'Check the NTP offset if target host',
                'command_id'                                => '15',
                'check_command_args'                        => '',
                'checkcommand_info'                         => '',
                'eventhandler_command_id'                   => '0',
                'timeperiod_id'                             => null,
                'check_interval'                            => '300',
                'retry_interval'                            => '90',
                'max_check_attempts'                        => '3',
                'first_notification_delay'                  => '0',
                'notification_interval'                     => '7200',
                'notify_on_warning'                         => '0',
                'notify_on_unknown'                         => '0',
                'notify_on_critical'                        => '1',
                'notify_on_recovery'                        => '1',
                'notify_on_flapping'                        => '0',
                'notify_on_downtime'                        => '0',
                'flap_detection_enabled'                    => '0',
                'flap_detection_on_ok'                      => '0',
                'flap_detection_on_warning'                 => '0',
                'flap_detection_on_unknown'                 => '0',
                'flap_detection_on_critical'                => '0',
                'low_flap_threshold'                        => '0',
                'high_flap_threshold'                       => '0',
                'process_performance_data'                  => '1',
                'freshness_checks_enabled'                  => '0',
                'freshness_threshold'                       => null,
                'passive_checks_enabled'                    => '0',
                'event_handler_enabled'                     => '0',
                'active_checks_enabled'                     => '1',
                'retain_status_information'                 => '0',
                'retain_nonstatus_information'              => '0',
                'notifications_enabled'                     => '0',
                'notes'                                     => '',
                'priority'                                  => '1',
                'tags'                                      => '',
                'service_url'                               => null,
                'is_volatile'                               => '0',
                'check_freshness'                           => '0',
                'created'                                   => '2015-01-16 00:10:54',
                'modified'                                  => '2015-01-16 00:10:54',
                'servicetemplateeventcommandargumentvalues' => [],
                'servicetemplatecommandargumentvalues'      => [
                    (int)0 => [
                        'id'                 => '28',
                        'commandargument_id' => '21',
                        'servicetemplate_id' => '17',
                        'value'              => '500',
                        'created'            => '2015-01-16 00:10:54',
                        'modified'           => '2015-01-16 00:10:54'
                    ],
                    (int)1 => [
                        'id'                 => '29',
                        'commandargument_id' => '22',
                        'servicetemplate_id' => '17',
                        'value'              => '1000',
                        'created'            => '2015-01-16 00:10:54',
                        'modified'           => '2015-01-16 00:10:54'
                    ]
                ],
                'customvariables'                           => [],
                'servicegroups'                             => [],
                'contactgroups'                             => [],
                'contacts'                                  => [
                    '_ids' => [
                        (int)0 => '1'
                    ]
                ]
            ],
            (int)17 => [
                'id'                                        => '18',
                'uuid'                                      => '9babe8f0-9012-47a8-8580-f82246365dd8',
                'template_name'                             => 'CHECK_NTP_TIME',
                'name'                                      => 'CHECK_NTP_TIME',
                'container_id'                              => '1',
                'servicetemplatetype_id'                    => '1',
                'check_period_id'                           => '1',
                'notify_period_id'                          => '1',
                'description'                               => 'Check the NTP offset if target host',
                'command_id'                                => '14',
                'check_command_args'                        => '',
                'checkcommand_info'                         => '',
                'eventhandler_command_id'                   => '0',
                'timeperiod_id'                             => null,
                'check_interval'                            => '300',
                'retry_interval'                            => '90',
                'max_check_attempts'                        => '3',
                'first_notification_delay'                  => '0',
                'notification_interval'                     => '7200',
                'notify_on_warning'                         => '0',
                'notify_on_unknown'                         => '0',
                'notify_on_critical'                        => '1',
                'notify_on_recovery'                        => '1',
                'notify_on_flapping'                        => '0',
                'notify_on_downtime'                        => '0',
                'flap_detection_enabled'                    => '0',
                'flap_detection_on_ok'                      => '0',
                'flap_detection_on_warning'                 => '0',
                'flap_detection_on_unknown'                 => '0',
                'flap_detection_on_critical'                => '0',
                'low_flap_threshold'                        => '0',
                'high_flap_threshold'                       => '0',
                'process_performance_data'                  => '1',
                'freshness_checks_enabled'                  => '0',
                'freshness_threshold'                       => null,
                'passive_checks_enabled'                    => '0',
                'event_handler_enabled'                     => '0',
                'active_checks_enabled'                     => '1',
                'retain_status_information'                 => '0',
                'retain_nonstatus_information'              => '0',
                'notifications_enabled'                     => '0',
                'notes'                                     => '',
                'priority'                                  => '1',
                'tags'                                      => '',
                'service_url'                               => null,
                'is_volatile'                               => '0',
                'check_freshness'                           => '0',
                'created'                                   => '2015-01-16 00:11:57',
                'modified'                                  => '2015-01-16 00:11:57',
                'servicetemplateeventcommandargumentvalues' => [],
                'servicetemplatecommandargumentvalues'      => [
                    (int)0 => [
                        'id'                 => '30',
                        'commandargument_id' => '19',
                        'servicetemplate_id' => '18',
                        'value'              => '500',
                        'created'            => '2015-01-16 00:11:57',
                        'modified'           => '2015-01-16 00:11:57'
                    ],
                    (int)1 => [
                        'id'                 => '31',
                        'commandargument_id' => '20',
                        'servicetemplate_id' => '18',
                        'value'              => '1000',
                        'created'            => '2015-01-16 00:11:57',
                        'modified'           => '2015-01-16 00:11:57'
                    ]
                ],
                'customvariables'                           => [],
                'servicegroups'                             => [],
                'contactgroups'                             => [],
                'contacts'                                  => [
                    '_ids' => [
                        (int)0 => '1'
                    ]
                ]
            ],
            (int)18  => [
                'id'                                        => '49',
                'uuid'                                      => 'a6cfd6e6-46b2-4385-9b1d-d035e8a9e9db',
                'template_name'                             => 'Statusengine Worker Performance',
                'name'                                      => 'Statusengine Worker Performance',
                'container_id'                              => '1',
                'servicetemplatetype_id'                    => '1',
                'check_period_id'                           => '1',
                'notify_period_id'                          => '1',
                'description'                               => '',
                'command_id'                                => '29',
                'check_command_args'                        => '',
                'checkcommand_info'                         => '',
                'eventhandler_command_id'                   => '0',
                'timeperiod_id'                             => null,
                'check_interval'                            => '60',
                'retry_interval'                            => '60',
                'max_check_attempts'                        => '3',
                'first_notification_delay'                  => '0',
                'notification_interval'                     => '0',
                'notify_on_warning'                         => '0',
                'notify_on_unknown'                         => '0',
                'notify_on_critical'                        => '1',
                'notify_on_recovery'                        => '1',
                'notify_on_flapping'                        => '0',
                'notify_on_downtime'                        => '0',
                'flap_detection_enabled'                    => '0',
                'flap_detection_on_ok'                      => '0',
                'flap_detection_on_warning'                 => '0',
                'flap_detection_on_unknown'                 => '0',
                'flap_detection_on_critical'                => '0',
                'low_flap_threshold'                        => '0',
                'high_flap_threshold'                       => '0',
                'process_performance_data'                  => '1',
                'freshness_checks_enabled'                  => '0',
                'freshness_threshold'                       => null,
                'passive_checks_enabled'                    => '0',
                'event_handler_enabled'                     => '0',
                'active_checks_enabled'                     => '1',
                'retain_status_information'                 => '0',
                'retain_nonstatus_information'              => '0',
                'notifications_enabled'                     => '0',
                'notes'                                     => '',
                'priority'                                  => '1',
                'tags'                                      => '',
                'service_url'                               => '',
                'is_volatile'                               => '0',
                'check_freshness'                           => '0',
                'created'                                   => '2015-01-05 15:20:14',
                'modified'                                  => '2015-01-15 23:46:17',
                'servicetemplateeventcommandargumentvalues' => [],
                'servicetemplatecommandargumentvalues'      => [],
                'customvariables'                           => [],
                'servicegroups'                             => [],
                'contactgroups'                             => [],
                'contacts'                                  => [
                    '_ids' => [
                        (int)0 => '1'
                    ]
                ]
            ],
        ];


        return $data;
    }
}
