<?php

//////////////////////////////////////////////////////////////////////////
//    DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN  //
//                                                                       //
//                   File generated by openITCOCKPIT                     //
//                                                                       //
//                        Created: 09.03.2021 10:18                      //
//////////////////////////////////////////////////////////////////////////


return [
    'gearman' => [
        'address'    => '127.0.0.1',
        'port'       => 4730,
        'pidfile'    => '/var/run/oitc_gearmanworker.pid',
        'worker'     => 5
    ]
];