<?php

//////////////////////////////////////////////////////////////////////////
//    DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN  //
//                                                                       //
//                   File generated by openITCOCKPIT                     //
//                                                                       //
//                        Created: 03.03.2021 09:42                      //
//////////////////////////////////////////////////////////////////////////


return [
    'gearman' => [
        'address'    => '127.0.0.1',
        'port'       => 4730,
        'encryption' => 1,
        'password'   => '3c3b0be215c95321c30de1ab908364dfbf0ed440',
        'pidfile'    => '/var/run/oitc_gearmanworker.pid',
        'worker'     => 5
    ]
];