<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'FreeDSx\\Ldap\\' => array($vendorDir . '/freedsx/ldap/src/FreeDSx/Ldap'),
    'FreeDSx\\Asn1\\' => array($vendorDir . '/freedsx/asn1/src/FreeDSx/Asn1'),
);
