<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit97ae95fccb8b24b3d49af23f8d958607
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'FreeDSx\\Ldap\\' => 13,
            'FreeDSx\\Asn1\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'FreeDSx\\Ldap\\' => 
        array (
            0 => __DIR__ . '/..' . '/freedsx/ldap/src/FreeDSx/Ldap',
        ),
        'FreeDSx\\Asn1\\' => 
        array (
            0 => __DIR__ . '/..' . '/freedsx/asn1/src/FreeDSx/Asn1',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit97ae95fccb8b24b3d49af23f8d958607::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit97ae95fccb8b24b3d49af23f8d958607::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
