<?php
// Copyright (C) <2018>  <it-novum GmbH>
//
// This file is dual licensed
//
// 1.
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, version 3 of the License.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
// 2.
//  If you purchased an openITCOCKPIT Enterprise Edition you can use this file
//  under the terms of the openITCOCKPIT Enterprise Edition license agreement.
//  License agreement and license key will be shipped with the order
//  confirmation.

namespace itnovum\openITCOCKPIT\ConfigGenerator;


class FileHeader {

    public function getHeader($commentChar = '#') {

        $headerLineLenght = ceil(73 / strlen($commentChar));

        $header = str_repeat($commentChar, $headerLineLenght) . PHP_EOL;
        $header .= sprintf('%s    DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN  %s%s', $commentChar, $commentChar, PHP_EOL);
        $header .= $commentChar . '                                                                       ' . $commentChar . PHP_EOL;
        $header .= $commentChar . '                   File generated by openITCOCKPIT                     ' . $commentChar . PHP_EOL;
        $header .= $commentChar . '                                                                       ' . $commentChar . PHP_EOL;
        $header .= sprintf('%s                        Created: %s                      %s%s', $commentChar, date('d.m.Y H:i'), $commentChar, PHP_EOL);
        $header .= str_repeat($commentChar, $headerLineLenght) . PHP_EOL;

        return $header;
    }
}
